### ISSUE TITLE
Monad from Adjunction

### ISSUE THREAD

**Issue by GenericMonkey** [maxsnew/multi-poly-cats#23]
Given L and R functors with `L ⊣ R`, show that `R ∘F L` is a monad

**Comment by maxsnew** [comment]
And by monad We mean `Control.Monad.Base`

**Comment by GenericMonkey** [comment]
I can't seem to locate this file -- i only see stuff in `Categories.Monad.Base`. Can you post a link?

**Comment by maxsnew** [comment]
just a typo

**Comment by stschaef** [comment]
Closed by #24
