### ISSUE TITLE
Functor Comprehension Principle/Principle of Unique Choice

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/multi-poly-cats#36]
I think a good name for the construction currently called `ParamUniversalElement→ProfRepresentation` is `FunctorComprehension` or the Principle of Unique Choice for Functors.

The reason is that its logical structure is a generalization of the *function* comprehension principle, which says if for a binary relation $R : X \times Y \to Prop$, if for every $x$ there exists a unique $y$ such that $R x y$ then there exists a (unique) function $f : X \to Y$ such that $x R f(x)$. 

Ours is similar except that it's about a Sigma type not an exists. Ours says (Version A) basically given `R : C^op x D -> Set` that
```
(∀ (c : C .ob) → TerminalObject (∫ᴾ (R c))) → Σ[ G ∈ Functor D C ] (R c d ≅ C [ c , G d ])
```
This is interesting without the squash since we construct the action on morphisms, but there 

But if `D` is univalent we should get the more squashed version (Version B):
```
isUnivalent D -> (∀ (c : C .ob) → HasTerminalObject (∫ᴾ (R c))) → ∃![ G ∈ Functor D C ] (R c d ≅ C [ c , G d ])
```

The main reason I bring this up is that I saw an [nlab page](https://ncatlab.org/nlab/show/functor+comprehension+principle) that uses the name "functor comprehension principle" for something else: that a fully faithful, eso functor has a pseudo-inverse. This gave me the idea that that, more well-known theorem is an instance of the FunctorComprehension theorem that @stschaef and @GenericMonkey . And since there's two versions of functor comprehension we should get two versions as well. Version A is that if a functor is fully faithful and [*split* essentially surjective](https://ncatlab.org/nlab/show/split+essentially+surjective+functor) then you can construct a pseudo inverse (in fact a right adjoint pseudo inverse). Version B is the usual one that if a functor $F : C \to D$ is fully faithful and essentially surjective (i.e., where you use an exists rather than a sigma) and $C$ is univalent then you can construct a right adjoint pseudo inverse.

So the plan would be
1. Prove Version B of the functor comprehension principle.
2. Prove Version A of constructing a pseudo inverse *using* Version A of the functor comprehension principle
3. Prove Version B of constructing a pseudo inverse *using* Version B of the functor comprehension principle.

**Comment by stschaef** [comment]
Been butting up against this same issue for a few days. I'm having some trouble with unique functor comprehension. For existence, it just suffices to take `F = FunctorComprehension ues .fst`, but then for uniqueness we need 

1. To construct a path between this `F` and any other `G` with `∀ (c : C .ob) → UniversalElementOn D (appR R c) (G ⟅ c ⟆)`
2. A path between the `.snd`'s. i.e. for all `c`, a`PathP` between `UniversalElementOn D (appR R c) (F ⟅ c ⟆)` and `UniversalElementOn D (appR R c) (G ⟅ c ⟆)`. I think this part *should* be easy given the first part. Something like a `cong` over the functor path? 

For 1., I can revive some old code to get a `NatIso` between `D [ - , F - ]` and `D [ - , G -]` as functors `C → D ^op → SET` (or equivalently out of `D ^op ×C C`), which feels close to the right thing. I would hope to reuse the proof that Yoneda is fully faithful, except the existing proof is for a slightly different Yoneda embedding than we have here. In any case, I can echo the details of that proof to get some fully faithful result here. The downside is that I think that only gives me a statement about objects.

That is, to use that Yoneda is fully faithful, I have to first plug in some `c`. To get `F .F-ob c  ≡ G .F-ob c` with nothing to say about morphisms. 

However, maybe I'm being silly here and there's enough info here to reason about morphism. Or maybe the `isUniversal` proofs give enough for that. Any ideas?

**Comment by maxsnew** [comment]
@stschaef Where did we leave this? Looking at the codebase it seems like we had some upstream changes that left a lot of old code commented out.

**Comment by stschaef** [comment]
Still roughly at the status of my previous scattered comment, where most of it is commented out with some holes around trying to prove the unique functor comprehension principle. 

I think there was some weird definitional issues between different versions of the Yoneda embedding, and I couldn't apply faithfulness in a nice way or something. I can set aside some time early next week to try to get this, and some of the other dangling issues, in order

**Comment by maxsnew** [comment]
Implemented in https://github.com/maxsnew/multi-poly-cats/pull/51
