### ISSUE TITLE
Changes in Upstream Cubical

### ISSUE THREAD

**Issue by stschaef** [maxsnew/multi-poly-cats#38]
`Cubical.Foundations.Id` is now deprecated. According a comment in the library, this should be replaced with `Cubical.Data.Equality`. Although, it's not as simple as just changing the name of the import. I think some of the internal functions have differing names now. I think it should still be a very simple fix. 

Here are the files affected:
- `./Cubical/Tactics/FunctorSolver/Examples.agda`
- `./Cubical/Tactics/FunctorSolver/Solver.agda`
- `./Cubical/Tactics/FunctorSolver/Reflection.agda`
- `./Cubical/Categories/Comonad/ExtensionSystem.agda`
- `./Cubical/Categories/Comonad/Instances/Environment.agda`
- `./Cubical/Categories/Comonad/Base.agda`
- `./Cubical/Categories/Constructions/Free/Functor.agda`
- `./Cubical/Categories/Profunctor/Equivalence.agda`
- `./Cubical/Categories/Monad/ExtensionSystem.agda`
- `./Cubical/Categories/Monad/Kleisli.agda`
- `./Cubical/Categories/Monad/Algebra.agda`
- `./Cubical/Categories/Monad/Strength/Cartesian/ExtensionSystem.agda`
- `./Cubical/Categories/DistributiveLaw/ComonadOverMonad/BiKleisli/Morphism.agda`
- `./Cubical/Categories/DistributiveLaw/ComonadOverMonad/BiKleisli/Base.agda`
- `./Cubical/Categories/DistributiveLaw/ComonadOverMonad/Base.agda`

Seemingly these all import from `Constructions.Free.Functor` and that should be the only one that we need to change

**Comment by maxsnew** [comment]
I have to fix this in my pr to cubical so I'm on it

**Comment by stschaef** [comment]
Now that that some of your stuff has been PR'd, is there convention for avoiding name clashes? For instance, if you load `Instances.Functors.More`, you get import errors for the category solver. 

It seems like the solution is to just delete all of the `multi-poly-cats` files that are now upstream, but this feels particularly weird when the solvers are still something we may need to do active development on. 

For now I'm just deleting these locally, but I feel like there should be a more principled solution

**Comment by maxsnew** [comment]
Probably the smarter thing to do would be to just work on our own fork of
`Cubical`

-Max Stewart New

**Comment by stschaef** [comment]
Lol I deleted this comment after double checking what you did in `cubical-update`, but I agree. Forking cubical directly will probably cause less headache when PRs get accepted
